# Generated by Django 4.1.7 on 2023-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
