# Generated by Django 4.1.7 on 2023-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_services_enable_alter_services_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='services',
            name='credit_type',
            field=models.IntegerField(verbose_name='Тип оплаты (0 - собственные средства, 2- кредит, 3 - рассрочка)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='desc',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Доступна'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(upload_to='static/images/services', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
