# Generated by Django 4.1.7 on 2023-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_services_options_alter_services_credit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(upload_to='images/services', verbose_name='Изображение'),
        ),
    ]
